// packages/@manifoldxyz-react/src/ConnectWidget.tsx
import React from 'react';
import { ConnectWidgetDataAttributes } from './shared/types';
import { Widget } from './Widget';

export const ConnectWidget: React.FC<{ version?: string } & ConnectWidgetDataAttributes> = ({
  version,
  ...props
}) => {
  return (
    <Widget
      widgetType="connect"
      version={version}
      dataAttributes={{
        ...props,
        widget: 'm-connect',
      }}
    ></Widget>
  );
};

// packages/@manifoldxyz-vue/src/ConnectWidget.vue
<script setup lang="ts">
import { computed } from 'vue';
import { ConnectWidgetDataAttributes } from './shared/types';
import Widget from './Widget.vue';

interface Props extends ConnectWidgetDataAttributes {
  version?: string;
}
const props = defineProps<Props>();
const dataAttributes = computed(() => {
  return {
    ...props,
    widget: 'm-connect',
  };
});
</script>
<template>
  <Widget :version="props.version" :data-attributes="dataAttributes"></Widget>
</template>
