// packages/@manifoldxyz-react/src/RestrictedTokenWidget.tsx
import React from 'react';
import { RestrictedTokenWidgetDataAttributes } from './shared/types';
import { Widget } from './Widget';

export const RestrictedTokenWidget: React.FC<
  { version: string } & RestrictedTokenWidgetDataAttributes
> = ({ version, ...props }) => {
  return (
    <Widget
      widgetType="restrictedToken"
      version={version}
      dataAttributes={{
        ...props,
        widget: 'm-restricted-token',
      }}
    ></Widget>
  );
};

// packages/@manifoldxyz-vue/src/RestrictedTokenWidget.vue
<script setup lang="ts">
import { computed } from 'vue';
import { RestrictedTokenWidgetDataAttributes } from './shared/types';
import Widget from './Widget.vue';

interface Props extends RestrictedTokenWidgetDataAttributes {
  version: string;
}
const props = defineProps<Props>();
const dataAttributes = computed(() => {
  return {
    ...props,
    widget: 'm-restricted-token',
  };
});
</script>
<template>
  <Widget :version="props.version" :data-attributes="dataAttributes"></Widget>
</template>
