// packages/@manifoldxyz-react/src/Widget.tsx
import React, { useEffect } from 'react';
import { WidgetType } from './shared/types';
import { camelCaseToHyphenCase, loadWidget } from './shared/utils';

export const Widget: React.FC<{
  widgetType: WidgetType;
  dataAttributes: { [key: string]: any };
  version?: string;
}> = ({ widgetType, dataAttributes, version }) => {
  useLoadWidget(widgetType, version);

  const dataAttributesHyphenated = Object.keys(dataAttributes).reduce(
    (acc: { [key: string]: any }, key) => {
      // @ts-ignore
      acc[`data-${camelCaseToHyphenCase(key)}`] = props[key];
      return acc;
    },
    {}
  );

  return <div {...dataAttributesHyphenated} dangerouslySetInnerHTML={{ __html: '' }}></div>;
};

const useLoadWidget = (widgetType: WidgetType, version?: string) => {
  return useEffect(() => {
    loadWidget(widgetType, version);
  }, [widgetType, version]);
};

// packages/@manifoldxyz-vue/src/Widget.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import { WidgetType } from './shared/types';
import { camelCaseToHyphenCase, loadWidget } from './shared/utils';

interface Props {
  widgetType: WidgetType;
  dataAttributes: { [key: string]: any };
  version?: string;
}

const props = defineProps<Props>();
const dataAttributesHyphenated = computed(() => {
  return Object.keys(props).reduce((acc: Partial<{ [key: string]: any }>, key) => {
    // @ts-ignore
    acc[`data-${camelCaseToHyphenCase(key)}`] = props[key];
    return acc;
  }, {} as Partial<{ [key: string]: any }>);
});

onMounted(() => {
  loadWidget(props.widgetType, props.version);
});
</script>
<template>
  <div v-bind="dataAttributesHyphenated"></div>
</template>
