// packages/@manifoldxyz-vue2/src/ConnectWidget.vue
<template>
  <div data-widget="m-connect" v-bind="propsAsDataAttributes"></div>
</template>
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { ConnectProps } from './shared/types';
import { camelCaseToHyphenCase, loadConnectWidget } from './shared/utils';

@Component
export default class ConnectWidget extends Vue {
  mounted() {
    loadConnectWidget();
  }

  get propsAsDataAttributes() {
    return Object.keys(this.$props).reduce((acc: Partial<ConnectProps>, key) => {
      // @ts-ignore
      acc[`data-${camelCaseToHyphenCase(key)}`] = props[key];
      return acc;
    }, {} as Partial<ConnectProps>);
  }
}
</script>

// packages/@manifoldxyz-react/src/ConnectWidget.tsx
import React, { useEffect } from 'react';
import { ConnectProps } from './shared/types';
import { camelCaseToHyphenCase, loadConnectWidget } from './shared/utils';

export const ConnectWidget: React.FC<ConnectProps> = (props) => {
  useConnect();

  const propsAsDataAttributes = Object.keys(props).reduce((acc: { [key: string]: any }, key) => {
    // @ts-ignore
    acc[`data-${camelCaseToHyphenCase(key)}`] = props[key];
    return acc;
  }, {});

  return (
    <div
      {...propsAsDataAttributes}
      data-widget="m-connect"
      dangerouslySetInnerHTML={{ __html: '' }}
    ></div>
  );
};

const useConnect = () => {
  return useEffect(() => {
    loadConnectWidget();
  }, []);
};
