// packages/@manifoldxyz-vue/src/MarketplaceWidget.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import Widget from './Widget.vue';
import { MarketplaceWidgetDataAttributes } from './shared/types'

interface Props extends MarketplaceWidgetDataAttributes {
  version?: string,
}

const { version, ...dataAttributes} = defineProps<Props>();
</script>
<template>
  <Widget :version="version" :dataAttributes="dataAttributes"></Widget>
</template>

// packages/@manifoldxyz-react/src/MarketplaceWidget.tsx
import React from 'react';
import { MarketplaceWidgetDataAttributes } from './shared/types';
import { Widget } from './Widget';

export const MarketplaceWidget: React.FC<
  { version?: string } & MarketplaceWidgetDataAttributes
> = ({ version, ...props }) => {
  return (
    <Widget
      widgetType="marketplace"
      version={version}
      dataAttributes={{
        ...props,
        version: 1,
      }}
    ></Widget>
  );
};
