// packages/@manifoldxyz-vue/src/WalletIdentityWidget.vue
<script setup lang="ts">
import { computed } from 'vue';
import { WalletIdentityWidgetDataAttributes } from './shared/types';
import Widget from './Widget.vue';

interface Props extends WalletIdentityWidgetDataAttributes {
  version: string;
}
const props = defineProps<Props>();
const dataAttributes = computed(() => {
  return {
    ...props,
    widget: 'm-wallet-identity',
  };
});
</script>
<template>
  <Widget :version="props.version" :data-attributes="dataAttributes"></Widget>
</template>

// packages/@manifoldxyz-react/src/WalletIdentityWidget.tsx
import React from 'react';
import { WalletIdentityWidgetDataAttributes } from './shared/types';
import { Widget } from './Widget';

export const WalletIdentityWidget: React.FC<
  { version: string } & WalletIdentityWidgetDataAttributes
> = ({ version, ...props }) => {
  return (
    <Widget
      widgetType="walletIdentity"
      version={version}
      dataAttributes={{
        ...props,
        widget: 'm-wallet-identity',
      }}
    ></Widget>
  );
};
